import Head from 'next/head'
import Link from 'next/link'
import { client } from '../libs/client'
import Header from '../components/organisms/Header'
import Container from '../components/templates/Container'
import SectionTitle from '../components/atoms/SectionTitle'
import ArchiveBlock from '../components/molecules/ArchiveBlock'


export default function Home({ blogs }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className='mt-20 lg:mt-40'>
        <Container size={1024}>
          <SectionTitle text="blog" />
          <ul>
            {blogs.map((blog) => (
             <ArchiveBlock key={blog.id} blog={blog} />
            ))}
          </ul>
        </Container>
      </section>
    </div>
  )
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: 'blog' })

  return {
    props: {
      blogs: data.contents,
    }
  }
}