import Head from 'next/head'
import Link from 'next/link'
import { client } from '../libs/client'

export default function Home({blog}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {blog.map((blog) => (
          <li key={blog.id}>
            <Link href={`/blog/${blog.id}`}>
              <a style={{color: 'white'}}>{blog.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}

export const getStaticProps = async () => {
  const data = await client.get({endpoint: 'blog'})

  return{
    props: {
      blog: data.contents,
    }
  }
}